name: dart_clean
description: dart_clean – clean dart and flutter repositories rercursively
version: 0.2.0
homepage: https://github.com/dartclub/dart_clean
repository: https://github.com/dartclub/dart_clean

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  yaml: ^3.1.2


dev_dependencies:
  lints: ^2.1.1

executables:
  dart_clean: main