name: dart_clean
description: dart_clean – clean dart and flutter repositories rercursively
version: 0.1.1
homepage: https://github.com/dartclub/dart_clean
repository: https://github.com/dartclub/dart_clean

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  yaml: ^2.2.1


dev_dependencies:
  dartclub_lint: ^0.2.1

executables:
  dart_clean: main